homework_5
evgeny-sivakov/React_01.24 pull request #6
Opened 2024-02-19 14:05 UTC by evgeny-sivakov

# Homework_5

<img width="910" alt="Screenshot 2024-02-19 at 14 53 59" src="https://github.com/evgeny-sivakov/React_01.24/assets/89925524/b9e50fa1-2b3c-43c5-a991-91b961d736bb">

>
<img width="852" alt="Screenshot 2024-02-19 at 14 54 22" src="https://github.com/evgeny-sivakov/React_01.24/assets/89925524/074b75e2-948b-4523-880c-9b03b49cca25">

>
Привет!
Я немного отстал. Зашился, потому что не мог найти источник странного поведения компонентов, но разобрался и получил полезный опыт. Но нужно учиться дебажить именно в реакте.

В целом приложение работает по условию верно. На некоторые комбинации запросов приходит ответ без данных, но обработки ошибок как таковой вроде делать не нужно было, поэтому я ошибку просто ловлю и в консоль вывожу.

2024-02-19 19:11 UTC, tagizade-samir requested changes
В целом все норм, но есть небольшой баг:
Если не выбирать например сложность, то пользователя пускает в приложение, но приложение крашится. Посмотри пожалуйста, чтобы если пользователь не выбирает значение для некоторых инпутов, чтобы его либо не пускало внутрь (если так задумано), либо чтобы пускало и работало корректно, так как АПИшка позволяет не указывать некоторые параметры и тогда они принимаются как any

2024-02-19 19:11 UTC, tagizade-samir commented on src/components/Question.jsx
> +      {console.log('question rerender')}
Лишний лог

2024-02-21 09:24 UTC, evgeny-sivakov commented on src/components/Question.jsx
> +      {console.log('question rerender')}
Привет!
Сделал, чтобы формировался конфиг по умолчанию.
Для этого функция convertFormData обрабатывает данные из формы перед отправкой их в редакс, а функция getConfigData формирует строку запроса. Она там принимает хинт, потому что я предположил, что может быть с ее помощью преобразую немного данные для отображения на странице результатов. Или может ее нужно вообще переделать в хук? 
Я просто не вижу до конца возможности для переиспользования такого хука, поэтому пока что написал просто функцию : )

2024-02-22 12:23 UTC, tagizade-samir commented on src/components/Question.jsx
> +      {console.log('question rerender')}
Переделать в хук тоже было бы супер

2024-02-22 13:02 UTC, evgeny-sivakov commented on src/components/Question.jsx
> +      {console.log('question rerender')}
Готово!

2024-02-22 13:08 UTC, tagizade-samir approved these changes

2024-02-22 14:51 UTC, merged